name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clj-kondo:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ["17"]
        clojure: ["1.10.1.693"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint clj-Kondo
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src test
          check-name: clj-kondo Result
          github_token: ${{ secrets.GITHUB_TOKEN }}

  eastwood:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ["17"]
        clojure: ["1.10.1.693"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          check-latest: false

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: ${{ matrix.clojure }}

      - name: Cache Clojure
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Lint
        run: clojure -M:eastwood
